apiVersion: v1
entries:
  restic-ops:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-25T16:41:44.935416+05:30"
    description: Production-ready Helm chart for restic-based Kubernetes backups with
      Backrest UI
    digest: ff2cf45d409cf22e25b45a973e5403c433fbffb3373fea9c49f824f4040691f6
    keywords:
    - backup
    - restic
    - kubernetes
    - cronjob
    - backrest
    maintainers:
    - email: ashwinijindal10@gmail.com
      name: Ashwini Jindal
    name: restic-ops
    urls:
    - https://ashwinijindal10.github.io/restic-ops-help-repo/charts/restic-ops-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-25T16:41:44.931753+05:30"
