apiVersion: v1
entries:
  restic-ops:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-25T17:34:45.730446+05:30"
    description: Production-ready Helm chart for restic-based Kubernetes backups with
      Backrest UI
    digest: d3a496350f612143ee8e5ff34a9a8338a9e4b650f7449787882fb9aa62e77625
    keywords:
    - backup
    - restic
    - kubernetes
    - cronjob
    - backrest
    maintainers:
    - email: ashwinijindal10@gmail.com
      name: Ashwini Jindal
    name: restic-ops
    urls:
    - https://ashwinijindal10.github.io/restic-ops-helm-repo/charts/restic-ops-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-25T17:34:45.729505+05:30"
