{{- if .Values.createBackupTargetPVCs }}
{{- range .Values.backup.targets }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvc }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
