{{- if .Values.enableBackrestUI }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backrest-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.ui.storageClass }}
  resources:
    requests:
      storage: {{ .Values.ui.storageSize }}
{{- end }}
